Full replace update
usdot-its-jpo-data-portal/sandbox pull request #7
Opened 2019-05-16 20:55 UTC by chuehlien

Modified lambda function for SPAT data set to perform full replace updates rather than perform upsert and deletion for each new data file.

Also modified the DTG data set cleanup script to remove records starting from those with the oldest generatedAt timestamp first.

2019-05-20 13:16 UTC, hmusavi requested changes

2019-05-20 13:16 UTC, hmusavi commented on source/lambda_functionspat.py
> +        if int(i.split('/')[6]) not in [8]:
Is this correct? Shouldn't it be the line above that is commented out?

2019-05-20 13:16 UTC, hmusavi commented on source/lambda_functionspat.py
> +        if int(i.split('/')[6]) not in [8]:
Let's define a constant for the hours array rather than hard-coding it.

2019-05-20 13:16 UTC, hmusavi commented on source/lambda_functionspat.py
> +    logger.info("Parsing data from the following hour directories: \n{}".format(",\n".join(hour_dirs)))
Suggestion: 
```
logger.info("Parsing data [NOT} from the following hour directories for the hours {}: \n{}".format(",\n".join(HOURS_CONSTANT, hour_dirs)))
```

2019-05-20 13:16 UTC, hmusavi commented on source/lambda_functionspat.py
> +        if int(i.split('/')[6]) not in [8]:
I'm confused. Are we looking for data within the specific hours or without? The comment sounds like within but `not in` excludes the given hours.

2019-05-20 13:16 UTC, hmusavi commented on source/lambda_functionspat.py
> +        key = "/".join(fp.split('/')[1:])
Please split once and use the array as many times as possible. could be a little more efficient.
```
bucket_path = fp.split('/')
bucket = bucket_path[0]
key = "/".join(bucket_path[1:])
```

2020-09-22 18:10 UTC, chuehlien commented
Closing this PR since the CVP lambda code had moved to the [cv_pilot_ingest repository](https://github.com/usdot-its-jpo-data-portal/cv_pilot_ingest).

2020-09-22 18:10 UTC, closed without merging